name: SendEmailAction

description: Sends an email using Gmail

inputs:
  subject:
    description: 'The subject of the email'
    required: true

runs:
  using: "composite"

  steps:
    - name: 'Create email file'
      shell: bash
      run: echo "Subject:${{ input.subject }}" 
        
