on: 
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Your job steps go here

      - name: Send Email Notification
        uses: vphanideep/test_actions@main
        with:
          recipient: phanideepchoudary888@gmail.com
          subject: Job Completed
          body: |
            The job has been completed successfully.
            Here are the details:
            - Step 1: Do something
            - Step 2: Do something else
          attachments: |
            path/to/attachment1.txt
            path/to/attachment2.pdf
