name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Demo Directory
        run: mkdir demo

      - name: Create Test File
        run: echo "This is a test file." > demo/test.txt

      - name: List Files
        run: ls demo

      - name: Send Email Notification
        run: pwd $runner_workspace
