name: Workspace and File Creation Example
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create and write to a file
        run: |
          mkdir mydir
          echo "Hello, GitHub Actions!" > mydir/myfile.txt

      - name: Display workspace contents
        run: ls -R

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: mydir
