name: email-sending

on: 
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send email notification
        uses: ./.github/actions/Email.yml
        with:
          subject: 'Job Completed'
          emailBody: |
            The job has been completed successfully.
            You can add more details here.
          recipient: phanideepchoudary888@gmail.com
          senderUsername: phanideepchoudary@gmail.com
          senderPassword: ${{ secrets.GMAIL_PASSWORD }}
